# Build
FROM node:10.4.0-alpine AS build

WORKDIR /opt/app
COPY web/package.json web/yarn.lock ./
RUN yarn install

COPY web ./
RUN yarn build

# Release
FROM nginx:1.15.0-alpine
MAINTAINER Agustin Carrasco <asermax@gmail.com>

COPY --from=build /opt/app/dist /usr/share/nginx/html
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
