version: '3'
services:
  proxy:
    image: nginx:1.13.12-alpine
    links:
      - api
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node:9.11.1-alpine
    volumes:
      - ./api:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
  web:
    image: node:9.11.1-alpine
    volumes:
      - ./web:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
