version: '3'
services:
  api:
    image: node:9.2-alpine
    volumes:
      - ./api:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: install
  web:
    image: node:9.2-alpine
    volumes:
      - ./web:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: install
