version: '3'
services:
  db:
    restart: always
  web:
    image: asermax/coopcon-web:0.4.0
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 80:80
    restart: always
  api:
    image: asermax/coopcon-api:0.4.0
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - api-deps:/opt/app/node_modules
    environment:
      - HOST=http://coopcon.tsuiseki.moe
    restart: always

volumes:
  api-deps:
