version: '3'
services:
  proxy:
    image: nginx:1.13.7-alpine
    links:
     - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node:9.2-alpine
    volumes:
      - ./api:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
  web:
    image: node:9.2-alpine
    volumes:
      - ./web:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
