version: '3'
services:
  proxy:
    image: nginx:1.15.0-alpine
    links:
      - api
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  api:
    image: node:10.4.0-alpine
    volumes:
      - ./api:/opt/app
    environment:
      - HOST=http://localhost
    entrypoint: /opt/app/entrypoint.sh
    command: start
  web:
    image: node:10.4.0-alpine
    volumes:
      - ./web:/opt/app
    entrypoint: /opt/app/entrypoint.sh
    command: start
