version: '3'
services:
  db:
    restart: always
  web:
    image: asermax/coopcon-web:0.2.1
    build: .
    ports:
      - 80:80
    restart: always
  api:
    image: asermax/coopcon-api:0.2.1
    build: api/
    volumes:
      - api-deps:/opt/app/node_modules
    restart: always

volumes:
  api-deps:
