version: '3'
services:
  api:
    links:
      - db
    environment:
      - PORT=80
      - MONGO_URL=mongodb://db:27017/coopcon
  db:
    image: mongo:3.6.4
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
